In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os

from sklearn import linear_model
from sklearn import metrics
from sklearn.decomposition import PCA

In [5]:
#importing all the files using the os module
folders = os.listdir('E:\Leak Detection Project\Hanoi_CMH') #You can also use full path.
folders.remove('Hanoi_CMH.inp')
folders.remove('Labels.csv')
# folders.remove('data1000sc.zip')

def Demands(Scenario):
    '''Used to get the Demand csv file with the Scenario name given as an argument'''
    Demands_L = []
    df1 = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\" + Scenario + "\\Demands\\Node_" + str(1) + '.csv')
    Demands_L.append(df1)
    for i in range(2,33):
        df = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Demands\\Node_" + str(i) + '.csv')
        df.rename(columns = {'Value':'Node'+str(i)}, inplace = True)
        Demands_L.append(df['Node'+str(i)])

    Demands = pd.concat(Demands_L, axis=1)
    Demands.set_index("Index", inplace = True)
    Demands.rename(columns = {'Value':'Node1'}, inplace = True)
    return Demands

    #Importing all the Flows from the Scenario 1 into a Dataframe
def Flows(Scenario):
    '''Used to get the Flows csv file with the Scenario name given as an argument'''
    Flows_L = []
    df1 = pd.read_csv (r'E:\Leak Detection Project\Hanoi_CMH\\'+ Scenario +'\\Flows\\Link_1.csv')
    Flows_L.append(df1)
    for i in range(2,35):
        df = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Flows\Link_" + str(i) + '.csv')
        df.rename(columns = {'Value':'Link'+str(i)}, inplace = True)
        Flows_L.append(df['Link'+str(i)])

    Flows = pd.concat(Flows_L, axis=1)
    Flows.set_index("Index", inplace = True)
    Flows.rename(columns = {'Value':'Link1'}, inplace = True)
    return Flows

    #Importing all the Pressures from the Scenario 1 into a Dataframe
def Pressures(Scenario):
    '''Used to get the Pressures csv file with the Scenario name given as an argument'''
    Pressures_L = []
    df1 = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Pressures\\Node_1.csv")
    Pressures_L.append(df1)
    for i in range(2,33):
        df = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Pressures\\Node_" + str(i) + '.csv')
        df.rename(columns = {'Value':'Node'+str(i)}, inplace = True)
        Pressures_L.append(df['Node'+str(i)])

    Pressures = pd.concat(Pressures_L, axis=1)
    Pressures.set_index("Index", inplace = True)
    Pressures.rename(columns = {'Value':'Node1'}, inplace = True)
    return Pressures

#Importing all the Leaks
Leaks = {}
folders = os.listdir('E:\Leak Detection Project\Hanoi_CMH') #You can also use full path.
folders.remove('Hanoi_CMH.inp')
folders.remove('Labels.csv')

for folder in folders:
    Leak = []
    files = os.listdir('E:\Leak Detection Project\Hanoi_CMH\\' + folder + '\\Leaks')
    
    if len(files) == 0 : 
        leak = None
        Leak.append(leak)
        Leaks[folder]= Leak
    if len(files) > 0:
        for i in range(1,len(files)+1,2):
            leak = pd.read_csv(r"E:\Leak Detection Project\Hanoi_CMH"+ '\\' + folder +'\\' + 'Leaks\\' + files[i])
            Leak.append(leak)
            Leaks[folder] = Leak

In [6]:
#Getting the attributes from the Flows from the dataset
Seq = []
for i in range(1,301):
    df_ = Flows('Scenario-' + str(i))
    Seq.append(df_.values.reshape(1,-1)[0])
# print(Seq)

#Getting the leak node from the leak database
Seql = list()
sc = list()

for i in range(1,301):
    try:
        k = list()
        for j in range(len(Leaks['Scenario-' + str(i)])):
            k.append(int(Leaks['Scenario-' + str(i)][j].values[0][1]))
        Seql.append(k)
    except:
        k = [0]
        Seql.append(k)
print(Seql)

[[0], [6], [13], [14], [0], [6], [10], [23], [7], [0], [12], [0], [21, 30], [0], [26, 3], [3], [20], [13, 29], [20], [15], [7], [2, 9], [4], [9], [31], [12], [0], [0], [0], [28], [28, 8], [9], [13, 21], [32, 9], [21, 26], [4], [11, 16], [3, 5], [20], [32], [22, 5], [30, 4], [22], [0], [21], [6], [12, 8], [0], [23], [23], [5], [20], [0], [20], [0], [19, 6], [16], [15], [21], [4], [19, 4], [15, 30], [30, 5], [8], [0], [3, 6], [0], [15], [25, 26], [17, 3], [9], [15, 31], [16, 18], [18, 30], [0], [8], [0], [22, 28], [23], [31], [0], [26], [0], [10], [23, 8], [32], [21, 30], [27], [23], [19], [2], [0], [17], [12], [14], [0], [5], [26], [3, 9], [0], [11, 14], [27, 5], [27], [2], [27], [2], [0], [16, 18], [11, 27], [7], [4], [0], [12, 2], [28], [7], [10], [3], [18], [21], [0], [14], [0], [25], [30, 3], [10], [30], [29], [13], [0], [27], [0], [21], [17, 26], [22], [28], [0], [0], [19, 3], [22], [22], [26, 7], [0], [18], [6], [7], [0], [29], [11, 20], [0], [18], [4], [7], [29, 31], [13, 3], [0]

In [31]:
# define list of places


# import json

# with open("E:\\Leak Detection Project\\test.txt", 'w') as f:
#     f.write(json.dumps(Seq))
    

# save numpy array as csv file
from numpy import asarray
from numpy import savetxt
# define data
# data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to csv file
savetxt("E:\\Leak Detection Project\\test.txt", Seq, delimiter=',')

In [3]:
target = []
for i in Seql:
    if i[0] ==  0:
        target.append(0)
    else: target.append(1)
print(target)

NameError: name 'Seql' is not defined

In [4]:
#Scaling and normalizing the data
from sklearn.preprocessing import StandardScaler, normalize
scaler = StandardScaler()
scaled_Seq = []
# for i in range(len(Seq)):
new = scaler.fit_transform(Seq)
new = normalize(Seq, norm='l2')
scaled_Seq.append(new)

scaled_Seq = np.array(scaled_Seq[0])
print(scaled_Seq)
print(scaled_Seq[0])

NameError: name 'Seq' is not defined

In [5]:
#Splitting the data into train set
trainx = np.array(Seq[:240]) 
trainy = np.array(target[:240])
trainx[0].shape
print(trainy)

#Splitting the data into the test set
testx = np.array(Seq[240:])
testy = np.array(target[240:])
print(testy)

scaled_trainx = np.array(scaled_Seq[:240])
scaled_testx = np.array(scaled_Seq[240:])

NameError: name 'Seq' is not defined

## Decision Tree

In [10]:
#Without Scaling and NOrmalization
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(trainx, trainy)

print(clf.score(trainx,trainy))
print(clf.score(testx,testy))
print(clf.get_depth())

1.0
0.7
6


In [12]:
#With Scaling and NOrmalization
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(scaled_trainx, trainy)

print(clf.score(scaled_trainx,trainy))
print(clf.score(scaled_testx,testy))
print(clf.get_depth())

1.0


KeyboardInterrupt: 

In [ ]:
#With Scaling and NOrmalization
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(min_samples_split = 5,
                              min_samples_leaf = 1,
                                 max_features= 'sqrt',
                                  max_depth= 3)
clf.fit(scaled_trainx, trainy)

print(clf.score(scaled_trainx,trainy))
print(clf.score(scaled_testx,testy))
print(clf.get_depth())

In [ ]:
#Tuning the parameters
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from pprint import pprint

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 100, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(1, 15, num = 15)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(trainx, trainy)

print(rf_random.best_params_)

## Random Forest

In [12]:
#Without Scaling and NOrmalization
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier()
clf_rf.fit(trainx,trainy)

print(clf_rf.score(trainx,trainy))
print(clf_rf.score(testx,testy))


1.0
0.7166666666666667


In [13]:
#With Scaling and NOrmalization
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier()
clf_rf.fit(scaled_trainx,trainy)

print(clf_rf.score(scaled_trainx,trainy))
print(clf_rf.score(scaled_testx,testy))

1.0
0.7833333333333333


In [14]:
#Tuning the parameters
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from pprint import pprint

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 100, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(1, 15, num = 15)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(trainx, trainy)

print(rf_random.best_params_)

{'bootstrap': [True, False],
 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]}
Fitting 3 folds for each of 10 candidates, totalling 30 fits
{'n_estimators': 70, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 3, 'bootstrap': True}


In [15]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(n_estimators= 70,
                               min_samples_split = 5,
                              min_samples_leaf = 1,
                                 max_features= 'sqrt',
                                  max_depth= 3,
                                 bootstrap= True)
clf_rf.fit(trainx, trainy)

print(clf_rf.score(trainx,trainy))
print(clf_rf.score(testx,testy))

0.8375
0.8333333333333334


## ANN

In [7]:
#Getting the attributes from the Flows from the dataset for the ANN model without reshaping the array
Seq_nf = []
for i in range(1,301):
    df_ = Flows('Scenario-' + str(i))
    Seq_nf.append(df_.values)
print(Seq_nf)

#Getting the leak node from the leak database
Seql = list()
sc = list()

for i in range(1,301):
    try:
        k = list()
        for j in range(len(Leaks['Scenario-' + str(i)])):
            k.append(int(Leaks['Scenario-' + str(i)][j].values[0][1]))
        Seql.append(k)
    except:
        k = [0]
        Seql.append(k)
print(len(Seql))

[array([[3337.2, 3186. , 1245.6, ...,  -72. ,   90. ,  223.2],
       [2973.6, 2836.8, 1130.4, ...,  -68.4,   82.8,  208.8],
       [2584.8, 2462.4,  982.8, ...,  -61.2,   72. ,  187.2],
       ...,
       [4791.6, 4586.4, 1832.4, ..., -111.6,  140.4,  334.8],
       [4406.4, 4197.6, 1684.8, ..., -104.4,  129.6,  295.2],
       [3981.6, 3798. , 1522.8, ...,  -86.4,  108. ,  273.6]]), array([[3232.8, 3092.4, 1209.6, ...,  -43.2,   61.2,  190.8],
       [2923.2, 2793.6, 1069.2, ...,  -39.6,   57.6,  165.6],
       [2577.6, 2462.4,  961.2, ...,  -39.6,   54. ,  158.4],
       ...,
       [4831.2, 4615.2, 1785.6, ...,  -54. ,   79.2,  277.2],
       [4334.4, 4136.4, 1638. , ...,  -57.6,   82.8,  262.8],
       [3981.6, 3812.4, 1494. , ...,  -54. ,   75.6,  223.2]]), array([[3330. , 3175.2, 1198.8, ...,  -28.8,   46.8,  212.4],
       [2944.8, 2822.4, 1087.2, ...,  -28.8,   43.2,  176.4],
       [2574. , 2466. ,  950.4, ...,  -28.8,   43.2,  162. ],
       ...,
       [4860. , 4633.2, 1774.

In [9]:
#Splitting the data into train set
trainx_nf = np.array(Seq_nf[:240]) 
trainy = np.array(target[:240])
# trainx[0].shape
print(trainx_nf)

#Splitting the data into the test set
testx_nf = np.array(Seq_nf[240:])
testy = np.array(target[240:])
print(testy)

# scaled_trainx = np.array(scaled_Seq[:240])
# scaled_testx = np.array(scaled_Seq[240:])

[[[3337.2 3186.  1245.6 ...  -72.    90.   223.2]
  [2973.6 2836.8 1130.4 ...  -68.4   82.8  208.8]
  [2584.8 2462.4  982.8 ...  -61.2   72.   187.2]
  ...
  [4791.6 4586.4 1832.4 ... -111.6  140.4  334.8]
  [4406.4 4197.6 1684.8 ... -104.4  129.6  295.2]
  [3981.6 3798.  1522.8 ...  -86.4  108.   273.6]]

 [[3232.8 3092.4 1209.6 ...  -43.2   61.2  190.8]
  [2923.2 2793.6 1069.2 ...  -39.6   57.6  165.6]
  [2577.6 2462.4  961.2 ...  -39.6   54.   158.4]
  ...
  [4831.2 4615.2 1785.6 ...  -54.    79.2  277.2]
  [4334.4 4136.4 1638.  ...  -57.6   82.8  262.8]
  [3981.6 3812.4 1494.  ...  -54.    75.6  223.2]]

 [[3330.  3175.2 1198.8 ...  -28.8   46.8  212.4]
  [2944.8 2822.4 1087.2 ...  -28.8   43.2  176.4]
  [2574.  2466.   950.4 ...  -28.8   43.2  162. ]
  ...
  [4860.  4633.2 1774.8 ...  -50.4   79.2  288. ]
  [4460.4 4258.8 1627.2 ...  -50.4   72.   277.2]
  [3974.4 3787.2 1468.8 ...  -46.8   64.8  226.8]]

 ...

 [[3348.  3193.2 1216.8 ...  -54.    75.6  212.4]
  [2959.2 2822.4 111

In [11]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras import datasets, layers, models
from keras import metrics

model = Sequential()

model.add(layers.Conv2D(2, kernel_size=3, strides=1, activation='relu', name = 'conv0',input_shape=(17520, 34,1)))
# model.add(layers.Conv2D(2, kernel_size=3, strides=1, activation='relu', name = 'conv0',input_shape=(48, 595680)))


model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(2, kernel_size=3, strides=1, activation='relu',name = 'conv1'))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

history = model.fit(
    trainx_nf,
    trainy,
    validation_data = (testx,testy),
    batch_size=48,
    epochs=10)

model.predict(testx_nf)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv0 (Conv2D)              (None, 17518, 32, 2)      20        
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 8759, 16, 2)      0         
 2D)                                                             
                                                                 
 conv1 (Conv2D)              (None, 8757, 14, 2)       38        
                                                                 
 flatten_2 (Flatten)         (None, 245196)            0         
                                                                 
 dense_6 (Dense)             (None, 32)                7846304   
                                                                 
 dense_7 (Dense)             (None, 16)                528       
                                                      

MemoryError: Unable to allocate 545. MiB for an array with shape (240, 17520, 34) and data type float32