In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os

from sklearn import linear_model
from sklearn import metrics
from sklearn.decomposition import PCA
# from sklearn.cross_validation import train_test_split

from sklearn.linear_model import LogisticRegression

## Importing all the necessary csv files of a single scenario

In [2]:
#Importing all the Demands from the Scenario 1 into a Dataframe
Demands_L = []
df1 = pd.read_csv (r"D:\Leak Detection Project\Hanoi_CMH\Scenario-1\Demands\Node_" + str(1) + '.csv')
Demands_L.append(df1)
for i in range(2,33):
    df = pd.read_csv (r"D:\Leak Detection Project\Hanoi_CMH\Scenario-1\Demands\Node_" + str(i) + '.csv')
    df.rename(columns = {'Value':'Node'+str(i)}, inplace = True)
    Demands_L.append(df['Node'+str(i)])

Demands = pd.concat(Demands_L, axis=1)
Demands.set_index("Index", inplace = True)
Demands.rename(columns = {'Value':'Node1'}, inplace = True)

#Importing all the Flows from the Scenario 1 into a Dataframe
Flows_L = []
df1 = pd.read_csv (r'D:\Leak Detection Project\Hanoi_CMH\Scenario-1\Flows\Link_1.csv')
Flows_L.append(df1)
for i in range(2,35):
    df = pd.read_csv (r"D:\Leak Detection Project\Hanoi_CMH\Scenario-1\Flows\Link_" + str(i) + '.csv')
    df.rename(columns = {'Value':'Link'+str(i)}, inplace = True)
    Flows_L.append(df['Link'+str(i)])

Flows = pd.concat(Flows_L, axis=1)
Flows.set_index("Index", inplace = True)
Flows.rename(columns = {'Value':'Link1'}, inplace = True)

#Importing all the Pressures from the Scenario 1 into a Dataframe
Pressures_L = []
df1 = pd.read_csv (r"D:\Leak Detection Project\Hanoi_CMH\Scenario-1\Pressures\Node_1.csv")
Pressures_L.append(df1)
for i in range(2,33):
    df = pd.read_csv (r"D:\Leak Detection Project\Hanoi_CMH\Scenario-1\Pressures\Node_" + str(i) + '.csv')
    df.rename(columns = {'Value':'Node'+str(i)}, inplace = True)
    Pressures_L.append(df['Node'+str(i)])

Pressures = pd.concat(Pressures_L, axis=1)
Pressures.set_index("Index", inplace = True)
Pressures.rename(columns = {'Value':'Node1'}, inplace = True)


print(Demands, Flows, Pressures)

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Leak Detection Project\\Hanoi_CMH\\Scenario-1\\Demands\\Node_1.csv'

## Importing data from all  the scenarios

In [2]:
folders = os.listdir('E:\Leak Detection Project\Hanoi_CMH') #You can also use full path.
folders.remove('Hanoi_CMH.inp')
folders.remove('Labels.csv')

def Demands(Scenario):
    Demands_L = []
    df1 = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\" + Scenario + "\\Demands\\Node_" + str(1) + '.csv')
    Demands_L.append(df1)
    for i in range(2,33):
        df = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Demands\\Node_" + str(i) + '.csv')
        df.rename(columns = {'Value':'Node'+str(i)}, inplace = True)
        Demands_L.append(df['Node'+str(i)])

    Demands = pd.concat(Demands_L, axis=1)
    Demands.set_index("Index", inplace = True)
    Demands.rename(columns = {'Value':'Node1'}, inplace = True)
    return Demands

    #Importing all the Flows from the Scenario 1 into a Dataframe
def Flows(Scenario):
    Flows_L = []
    df1 = pd.read_csv (r'E:\Leak Detection Project\Hanoi_CMH\\'+ Scenario +'\\Flows\\Link_1.csv')
    Flows_L.append(df1)
    for i in range(2,35):
        df = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Flows\Link_" + str(i) + '.csv')
        df.rename(columns = {'Value':'Link'+str(i)}, inplace = True)
        Flows_L.append(df['Link'+str(i)])

    Flows = pd.concat(Flows_L, axis=1)
    Flows.set_index("Index", inplace = True)
    Flows.rename(columns = {'Value':'Link1'}, inplace = True)
    return Flows

    #Importing all the Pressures from the Scenario 1 into a Dataframe
def Pressures(Scenario):
    Pressures_L = []
    df1 = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Pressures\\Node_1.csv")
    Pressures_L.append(df1)
    for i in range(2,33):
        df = pd.read_csv (r"E:\Leak Detection Project\Hanoi_CMH\\"+ Scenario +"\\Pressures\\Node_" + str(i) + '.csv')
        df.rename(columns = {'Value':'Node'+str(i)}, inplace = True)
        Pressures_L.append(df['Node'+str(i)])

    Pressures = pd.concat(Pressures_L, axis=1)
    Pressures.set_index("Index", inplace = True)
    Pressures.rename(columns = {'Value':'Node1'}, inplace = True)
    return Pressures
    


## Plotting the values to find more about the data

## Importing Leaks from various scenarios

In [3]:
Leaks = {}
folders = os.listdir('E:\Leak Detection Project\Hanoi_CMH') #You can also use full path.
folders.remove('Hanoi_CMH.inp')
folders.remove('Labels.csv')

for folder in folders:
    Leak = []
    files = os.listdir('E:\Leak Detection Project\Hanoi_CMH\\' + folder + '\\Leaks')

    if len(files) == 0 : 
        leak = None
        Leak.append(leak)
        Leaks[folder]= Leak
    if len(files) > 0:
        for i in range(1,len(files)+1,2):
            leak = pd.read_csv(r"E:\Leak Detection Project\Hanoi_CMH"+ '\\' + folder +'\\' + 'Leaks\\' + files[i])
            Leak.append(leak)
            Leaks[folder] = Leak

# print(Leaks)


# Making use of the pressure and the flow with Leaks to create a simple classifier

# Machine Learning Models

In [59]:
Seq = []
# df_ = Pressures('Scenario-1')
# df_.values

for i in range(1,500):
    df_ = Pressures('Scenario-' + str(i))
    Seq.append(df_.values.reshape(1,-1)[0])
    #Seq = Seq.join(df_.values)
Seq

[array([ 0.   , 69.887, 66.305, ..., 62.417, 62.47 , 62.59 ]),
 array([ 0.   , 69.792, 67.95 , ..., 65.748, 65.768, 65.826]),
 array([ 0.   , 69.946, 67.545, ..., 65.051, 65.085, 65.143]),
 array([ 0.   , 69.902, 68.502, ..., 65.943, 65.951, 65.978]),
 array([ 0.   , 69.923, 68.944, ..., 67.139, 67.141, 67.15 ]),
 array([ 0.   , 69.932, 68.294, ..., 65.245, 65.281, 65.347]),
 array([ 0.   , 69.853, 68.542, ..., 65.994, 66.012, 66.07 ]),
 array([ 0.   , 69.84 , 68.719, ..., 66.418, 66.436, 66.481]),
 array([ 0.   , 69.877, 68.681, ..., 66.586, 66.604, 66.67 ]),
 array([ 0.   , 69.935, 68.744, ..., 66.751, 66.771, 66.846]),
 array([ 0.   , 69.931, 68.794, ..., 66.827, 66.859, 66.965]),
 array([ 0.   , 69.87 , 68.741, ..., 66.719, 66.733, 66.789]),
 array([ 0.   , 69.871, 69.066, ..., 67.056, 67.081, 67.159]),
 array([ 0.   , 69.889, 67.799, ..., 65.482, 65.517, 65.655]),
 array([ 0.   , 69.942, 68.797, ..., 66.53 , 66.588, 66.698]),
 array([ 0.   , 69.901, 68.604, ..., 66.26 , 66.274, 66

In [60]:
#Getting the leak node from the leak database
Seql = list()
sc = list()

for i in range(1,500):
    try:
        k = list()
        for j in range(len(Leaks['Scenario-' + str(i)])):
            k.append(int(Leaks['Scenario-' + str(i)][j].values[0][1]))
        Seql.append(k)
    except:
        k = [0]
        Seql.append(k)
print(Seql)

[[0], [6], [13], [14], [0], [6], [10], [23], [7], [0], [12], [0], [21, 30], [0], [26, 3], [3], [20], [13, 29], [20], [15], [7], [2, 9], [4], [9], [31], [12], [0], [0], [0], [28], [28, 8], [9], [13, 21], [32, 9], [21, 26], [4], [11, 16], [3, 5], [20], [32], [22, 5], [30, 4], [22], [0], [21], [6], [12, 8], [0], [23], [23], [5], [20], [0], [20], [0], [19, 6], [16], [15], [21], [4], [19, 4], [15, 30], [30, 5], [8], [0], [3, 6], [0], [15], [25, 26], [17, 3], [9], [15, 31], [16, 18], [18, 30], [0], [8], [0], [22, 28], [23], [31], [0], [26], [0], [10], [23, 8], [32], [21, 30], [27], [23], [19], [2], [0], [17], [12], [14], [0], [5], [26], [3, 9], [0], [11, 14], [27, 5], [27], [2], [27], [2], [0], [16, 18], [11, 27], [7], [4], [0], [12, 2], [28], [7], [10], [3], [18], [21], [0], [14], [0], [25], [30, 3], [10], [30], [29], [13], [0], [27], [0], [21], [17, 26], [22], [28], [0], [0], [19, 3], [22], [22], [26, 7], [0], [18], [6], [7], [0], [29], [11, 20], [0], [18], [4], [7], [29, 31], [13, 3], [0]

In [61]:
#Creating a dataframe for the target values to be used in the Decision Tree classifier shape = (100,32) using pressures
cols = [i for i in range(1,33)]
ind = [i for i in range(1,len(Seql)+1)]
target = pd.DataFrame(np.zeros((len(Seql),32)), columns = cols, index = ind)

for i in range(len(Seql)):
    for j in range(len(Seql[i])):
        if Seql[i][j] == 0 : continue
        target[Seql[i][j]][i+1] = 1

target

1    2    3    4    5    6    7    8    9    10  ...   23   24   25  \
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
496  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
497  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
498  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
499  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      26   27   28   29   30   31   32  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
496  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
497  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
498  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
499  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[499 rows x 32 columns]

In [87]:
#Splitting the data into train set
trainx = Seq[:400] 
trainy = target[:][:400]
trainx[0].shape
print(trainy)

#Splitting the data into the test set
testx = Seq[400:]
testy = target[:][400:]
print(testy,testx)

      1    2    3    4    5    6    7    8    9    10  ...   23   24   25  \
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
396  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
397  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
398  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
399  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
400  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      26   27   28   29   30   31   32  
1    0.0  0.0  0.0  0.0  0.0  0.0 

## sklearn.tree.DecisionTreeClassifier

Taken 100 Scenarios from the Demand database.

Divided it into train and test by using 75 Scenarios for train and 25 Scenarios for test.

Created a dataframe for the labels of the data whose shape is (100,32)

Using the DecisionTree Classifier fitted the model on all the features(which were flattened from the data).

[If possible use PCA to find out the best features of the data and use it in the model]

The Accuracy is not very good. The reasons may be due to:
- The data taken is very less and hence the model may not be able to generalize the patterns in the data
- Maybe too many features are present in the data and hence we are not able to get the desired output.
- Maybe the model is not suitable for this data and I need to try out different models and compare the results.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

clf = DecisionTreeClassifier(random_state=0)
clf.fit(trainx, trainy)

In [10]:
predy = clf.predict(testx)
print(testy)

NameError: name 'clf' is not defined

In [24]:
# testy_converted = mlb.transform(testy)
# print(testy_converted)
# print(testy_converted.shape, x_pca_test.shape)
clf.score(testx,testy)

0.16

In [26]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(testy,predy)
# accuracy_score(train)

0.16

In [143]:
clf = LogisticRegression(random_state=0, multi_class= 'multinomial')
clf.fit(trainx, trainy)

ValueError: y should be a 1d array, got an array of shape (75, 32) instead.

## PCA to reduce the dimensionality of the data

In [88]:
pca = PCA(n_components= 100, svd_solver = 'full')
pca.fit(trainx)
#x_pca = pca.transform(trainx)
# print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

PCA(n_components=100, svd_solver='full')

In [92]:
print(pca.explained_variance_ratio_[:100].sum())

0.9901401785944696


In [93]:
trainx_pca = pca.transform(trainx)
testx_pca = pca.transform(testx)

## sklearn.ensemble.RandomForestClassifier

In [95]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(n_estimators= 50,
                               
                              
                                 max_features= 'sqrt',
#                                   max_depth= 35,
                                 bootstrap= True,
                                random_state=0,)



RandomForestClassifier(max_features='sqrt', n_estimators=50, random_state=0)

In [82]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 50, stop = 500, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(7, 30, num = 15)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(trainx_pca, trainy)

{'bootstrap': [True, False],
 'max_depth': [7, 8, 10, 11, 13, 15, 16, 18, 20, 21, 23, 25, 26, 28, 30, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]}
Fitting 3 folds for each of 10 candidates, totalling 30 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [7, 8, 10, 11, 13, 15, 16,
                                                      18, 20, 21, 23, 25, 26,
                                                      28, 30, None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 150, 200, 250,
                                                         300, 350, 400, 450,
                                                         500]},
                   random_state=42, verbose=2)

In [84]:
rf_random.best_params_

{'n_estimators': 50,
 'min_samples_split': 10,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 13,
 'bootstrap': True}

In [16]:
from pprint import pprint
pprint(clf_rf.get_params())

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 15,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 0,
 'verbose': 0,
 'warm_start': False}


In [98]:
from sklearn.metrics import accuracy_score

# pred_y = clf_rf.predict(testx)
# print(accuracy_score(testy,pred_y))
# print(clf_rf.score(testx, testy, sample_weight=None))
print((clf_rf.score(trainx_pca,trainy), clf_rf.score(testx_pca,testy)))

(0.975, 0.23232323232323232)


## sklearn.ensemble.ExtraTreesClassifier

In [119]:
from sklearn.ensemble import ExtraTreesClassifier
clf_et = ExtraTreesClassifier(n_estimators=50, random_state=0)
clf_et.fit(trainx_pca,trainy)

ExtraTreesClassifier(n_estimators=50, random_state=0)

In [120]:
pred_y = clf_et.predict(testx_pca)
# print(accuracy_score(testy,pred_y))
# print(clf_et.score(testx_pca, testy))
# print(clf_et.score(trainx, trainy))
print((clf_et.score(trainx_pca,trainy), clf_et.score(testx_pca,testy)))

(1.0, 0.23232323232323232)


## sklearn.ensemble.GradientBoostingClassifier

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
clf_gb = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
clf_gb.fit(trainx,trainy)

ValueError: y should be a 1d array, got an array of shape (75, 32) instead.

In [124]:
import xgboost as xgb
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score

# create sample dataset
# X, y = make_multilabel_classification(n_samples=3000, n_features=45, n_classes=20, n_labels=1,
#                                       allow_unlabeled=False, random_state=42)

# split dataset into training and test set
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# create XGBoost instance with default hyper-parameters
xgb_estimator = xgb.XGBClassifier(objective='binary:logistic')

# create MultiOutputClassifier instance with XGBoost model inside
multilabel_model = MultiOutputClassifier(xgb_estimator)

# fit the model
multilabel_model.fit(trainx_pca, trainy)

# evaluate on test data
print('Accuracy on test data: {:.1f}%'.format(accuracy_score(testy, multilabel_model.predict(testx_pca))*100))

C:\Users\parimiharsha\anaconda3\envs\LeakDB\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[18:15:02] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[18:15:02] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[18:15:02] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[18:15:02] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old be

# Deep Learning Models

## CNN s

In [14]:
import tensorflow as tf
from tensorflow import keras
# model = models.Sequential()
# model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))
# model.add(layers.MaxPooling2D((2, 2)))
# model.add(layers.Conv2D(64, (3, 3), activation='relu'))

def make_model(input_shape):
    input_layer = keras.layers.Input(input_shape)

    conv1 = keras.layers.Conv1D(filters=64, kernel_size=3, padding="same")(input_layer)
    conv1 = keras.layers.BatchNormalization()(conv1)
    conv1 = keras.layers.ReLU()(conv1)

    conv2 = keras.layers.Conv1D(filters=64, kernel_size=3, padding="same")(conv1)
    conv2 = keras.layers.BatchNormalization()(conv2)
    conv2 = keras.layers.ReLU()(conv2)

    conv3 = keras.layers.Conv1D(filters=64, kernel_size=3, padding="same")(conv2)
    conv3 = keras.layers.BatchNormalization()(conv3)
    conv3 = keras.layers.ReLU()(conv3)

    gap = keras.layers.GlobalAveragePooling1D()(conv3)

    output_layer = keras.layers.Dense(num_classes, activation="softmax")(gap)

    return keras.models.Model(inputs=input_layer, outputs=output_layer)


model = make_model(input_shape=len(trainx[0]))
keras.utils.plot_model(model, show_shapes=True)

ValueError: Input 0 of layer "conv1d" is incompatible with the layer: expected min_ndim=3, found ndim=2. Full shape received: (None, 560640)

## LSTM Model 

In [ ]:
model = Sequential()
model.add(LSTM(256, input_shape=(seq_len, 4)))
model.add(Dense(1, activation='sigmoid'))